# Generated by Django 5.0.1 on 2024-01-23 20:42

import gacdsl.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacdsl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', gacdsl.managers.DiscordUserOAuth2Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
