# Generated by Django 5.0.1 on 2024-01-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacdsl', '0002_alter_discorduser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamerUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('twitch_url', models.CharField(max_length=250)),
                ('card_num', models.IntegerField()),
                ('balance', models.BigIntegerField()),
                ('unic_link', models.CharField(max_length=250)),
                ('min_donate', models.IntegerField()),
            ],
        ),
    ]
